language: bash
servics: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - image="mai1015/php_composer:latest"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images